[package]
name = "dark-sky"
version = "3.0.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]

[dependencies]
alphred = { path = "../alphred-rs" }
chrono = "0.4"
error-chain = "0.11"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
